title = "J1439+76"

[Name]
value = "J1439+76"
error = false
ref = "https://doi.org/10.1088/0004-637X/809/1/67"

[RA]
value = "14:39" #hh:mm:ss.ss
error = "00:02"
ref = "https://doi.org/10.1088/0004-637X/809/1/67"

[Dec]
value = "+76:55" #(sign)dd:mm:ss.ss
error = "00:36"
ref = "https://doi.org/10.1088/0004-637X/809/1/67"

[DM]
value =  22.29 #pc/cc
error = 0.02
ref = "https://doi.org/10.1088/0004-637X/809/1/67"

[Period]
value = 0.947903 #seconds
error = 0.000002
ref = "https://doi.org/10.1088/0004-637X/809/1/67"

[Width]

    [Width.350]
  value= 6 #ms
  error = false
  frequency = 350 #MHz
  ref = "https://doi.org/10.3847/1538-4357/ab75e2"

[Flux]

    [Flux.350]
  value= 0.41 #mJy
  error = 0.09
  frequency = 350 #MHz
  ref = "https://doi.org/10.3847/1538-4357/ab75e2"


[BurstRate]

    [BurstRate.Discovery]
  value= 450
  error= 116
  frequency= 350
  telescope= 'GBT'
  minflux= 160 #mJy
  ref = "https://doi.org/10.1088/0004-637X/809/1/67"

    [BurstRate.GBT350]
  value= 406
  error= 48
  frequency= 350
  telescope= 'GBT'
  minflux= 160 #mJy
  ref = "https://doi.org/10.1088/0004-637X/809/1/67"

    [BurstRate.GBT820]
  value= 0
  error= false
  frequency= 820
  telescope= 'GBT'
  minflux= 45 #mJy
  ref = "https://doi.org/10.1088/0004-637X/809/1/67"

    [BurstRate.LOFAR]
  value= 0
  error= false
  frequency= 150
  telescope= 'LOFAR'
  minflux= 80 #mJy
  ref = "https://doi.org/10.1088/0004-637X/809/1/67"



#Karako-Argaman et al 2015: https://doi.org/10.1088/0004-637X/809/1/67
#McEwen et al 2020: https://doi.org/10.3847/1538-4357/ab75e2
