title = "J1819-1458"

[Name]
value = "J1819-1458"
error = false
ref = "https://doi.org/10.1038/nature04440"

[RA]
value = "18:19:34.16" #hh:mm:ss.ss
error = "00:00:00.01"
ref = "https://doi.org/10.1093/mnras/sty923"

[Dec]
value = "-14:58:03.57" #(sign)dd:mm:ss.ss
error = "00:00:00.01"
ref = "https://doi.org/10.1093/mnras/sty923"

[DM]
value = 196.0 #pc/cc
error = 0.4
ref = "https://doi.org/10.1111/j.1365-2966.2008.13669.x"

[Period]
value = 4.26321348 #seconds
error = 0.00000008
ref = "https://doi.org/10.1093/mnras/sty923"

[Pdot]
value = 562.68e-15 #s/s
error = 0.08e-15
ref = "https://doi.org/10.1093/mnras/sty923"

[Flux]

    [Flux.1400]
  value = 3600 #mJy
  error = false
  frequency = 1400 #MHz
  ref = "https://doi.org/10.1038/nature04440"

[Width]

    [Width.1400]
  value = 3 #ms
  error = false
  frequency = 1400 #MHz
  ref = "https://doi.org/10.1038/nature04440"

[BurstRate]

    [BurstRate.Discovery]
  value= 17.6 #hour^-1
  error= false
  frequency= 1400 #MHz
  telescope= "Parkes"
  minflux= 150 #mJy
  ref = "https://doi.org/10.1038/nature04440"

#McLaughlin et al 2006: https://doi.org/10.1038/nature04440
#Esamdin et al 2008: https://doi.org/10.1111/j.1365-2966.2008.13669.x
#Bhattacharyya et al 2018: https://doi.org/10.1093/mnras/sty923
