title = "J1859+07"

[Name]
value = "J1859+07"
error = false
ref = "https://doi.org/10.3847/1538-4357/aaee65"

[RA]
value = "18:59" #hh:mm:ss.ss
error = false
ref = "https://doi.org/10.3847/1538-4357/aaee65"

[Dec]
value = "+07" #(sign)dd:mm:ss.ss
error = false
ref = "https://doi.org/10.3847/1538-4357/aaee65"

[DM]
value = 303.1 #pc/cc
error = 2.2
ref = "https://doi.org/10.3847/1538-4357/aaee65"

[Flux]

    [Flux.1400]
  value = 20 #mJy
  error = false
  frequency = 1400 #MHz
  ref = "https://doi.org/10.3847/1538-4357/aaee65"

[Width]

    [Width.1400]
  value = 4.5 #ms
  error = false
  frequency = 1400 #MHz
  ref = "https://doi.org/10.3847/1538-4357/aaee65"


#Deneva et al 2018: https://doi.org/10.3847/1538-4357/aaee65
