title = "J1911+00"

[Name]
value = "J1911+00"
error = false
ref = "https://doi.org/10.1038/nature04440"

[RA]
value = "19:11:48" #hh:mm:ss.ss
error = "00:00:29"
ref = "https://doi.org/10.1111/j.1365-2966.2011.18917.x"

[Dec]
value = "+00:37" #(sign)dd:mm:ss.ss
error = "00:07"
ref = "https://doi.org/10.1111/j.1365-2966.2011.18917.x"

[DM]
value = 100 #pc/cc
error = 3
ref = "https://doi.org/10.1038/nature04440"

[Period]
value = 6.94 #seconds
error = 0.01
ref = "https://doi.org/10.1111/j.1365-2966.2011.18917.x"

[Flux]

    [Flux.1400]
  value = 250 #mJy
  error = false
  frequency = 1400 #MHz
  ref = "https://doi.org/10.1038/nature04440"

[Width]

    [Width.1400]
  value = 5 #ms
  error = false
  frequency = 1400 #MHz
  ref = "https://doi.org/10.1038/nature04440"

[BurstRate]

    [BurstRate.Discovery]
  value= 0.31 #hour^-1
  error= false
  frequency= 1400 #MHz
  telescope= "Parkes"
  minflux= 120 #mJy
  ref = "https://doi.org/10.1038/nature04440"

#McLaughlin et al 2006: https://doi.org/10.1038/nature04440
#Keane et al 2011: https://doi.org/10.1111/j.1365-2966.2011.18917.x 
