title = "J1952+30"

[Name]
value = "J1952+30"
error = false
ref = "https://doi.org/10.3847/1538-4357/aaee65"

[RA]
value = "19:52" #hh:mm:ss.ss
error = false
ref = "https://doi.org/10.3847/1538-4357/aaee65"

[Dec]
value = "+30" #(sign)dd:mm:ss.ss
error = false
ref = "https://doi.org/10.3847/1538-4357/aaee65"

[DM]
value = 188.8 #pc/cc
error = 0.6
ref = "https://doi.org/10.3847/1538-4357/aaee65"

[Period]
value = 1.66560 #seconds
error = 0.00012
ref = "https://doi.org/10.3847/1538-4357/aaee65"

[Flux]

    [Flux.1400]
  value = 33 #mJy
  error = false
  frequency = 1400 #MHz
  ref = "https://doi.org/10.3847/1538-4357/aaee65"

[Width]

    [Width.1400]
  value = 5.7 #ms
  error = false
  frequency = 1400 #MHz
  ref = "https://doi.org/10.3847/1538-4357/aaee65"


#Deneva et al 2018: https://doi.org/10.3847/1538-4357/aaee65
