title = "J2000+29"

[Name]
value = "J2000+29"
error = false
ref = "https://doi.org/10.3847/1538-4357/aaee65"

[RA]
value = "20:00" #hh:mm:ss.ss
error = false
ref = "https://doi.org/10.3847/1538-4357/aaee65"

[Dec]
value = "+29" #(sign)dd:mm:ss.ss
error = false
ref = "https://doi.org/10.3847/1538-4357/aaee65"

[DM]
value = 132.3 #pc/cc
error = 0.7
ref = "https://doi.org/10.3847/1538-4357/ab75e2"

[Period]
value = 3.07370 #seconds
error = 0.00014
ref = "https://doi.org/10.3847/1538-4357/aaee65"

[Flux]

    [Flux.1400]
  value = 159 #mJy
  error = false
  frequency = 1400 #MHz
  ref = "https://doi.org/10.3847/1538-4357/aaee65"

    [Flux.350]
  value= 1.4 #mJy
  error = 0.3
  frequency = 350 #MHz
  ref = "https://doi.org/10.3847/1538-4357/ab75e2"


[Width]

    [Width.1400]
  value = 7.4 #ms
  error = false
  frequency = 1400 #MHz
  ref = "https://doi.org/10.3847/1538-4357/aaee65"

    [Width.350]
  value= 23 #ms
  error = false
  frequency = 350 #MHz
  ref = "https://doi.org/10.3847/1538-4357/ab75e2"



#Deneva et al 2018: https://doi.org/10.3847/1538-4357/aaee65
#McEwen et al 2020: https://doi.org/10.3847/1538-4357/ab75e2
