title = "J0054+69"

[Name]
value = "J0054+69"
error = false
ref = "https://doi.org/10.1088/0004-637X/809/1/67"

[RA]
value = "00:54:28"  # hh:mm:ss.ss
error = "00:00:25"
ref = "https://doi.org/10.1088/0004-637X/809/1/67"

[Dec]
value = "+69:26"  # (sign)dd:mm:ss.ss
error = "00:02"
ref = "https://doi.org/10.1088/0004-637X/809/1/67"

[DM]
value = 90.3  # pc/cm^3
error = 0.2
ref = "https://doi.org/10.1088/0004-637X/809/1/67"

[BurstRate]
[BurstRate.Discovery]
value = 300
error = 95
frequency = 350
telescope = "GBT"
minflux = 160  # mJy
ref = "https://doi.org/10.1088/0004-637X/809/1/67"

[BurstRate.GBT350]
value = 186
error = 33
frequency = 350
telescope = "GBT"
minflux = 160  # mJy
ref = "https://doi.org/10.1088/0004-637X/809/1/67"

[BurstRate.GBT820]
value = 285
error = 21
frequency = 820
telescope = "GBT"
minflux = 45  # mJy
ref = "https://doi.org/10.1088/0004-637X/809/1/67"

[BurstRate.LOFAR]
value = 6
error = 2
frequency = 150
telescope = "LOFAR"
minflux = 80  # mJy
ref = "https://doi.org/10.1088/0004-637X/809/1/67"

# Karako-Argaman et al 2015: https://doi.org/10.1088/0004-637X/809/1/67
