title = "J0102+5356"

[Name]
value = "J0102+5356"
error = false
ref = "https://doi.org/10.1093/mnras/stad2900"

[RA]
value = "01:02:57.786"  # hh:mm:ss.ss
error = "00:00:00.012"
ref = "https://doi.org/10.1093/mnras/stad2900"

[Dec]
value = "+53:56:11.86"  # (sign)dd:mm:ss.ss
error = "00:00:00.15"
ref = "https://doi.org/10.1093/mnras/stad2900"

[DM]
value = 55.6200  # pc/cc
error = 0.0008
ref = "https://doi.org/10.1093/mnras/stad2900"

[Period]
value = 0.354299198996  # seconds
error = 0.000000000004
ref = "https://doi.org/10.1093/mnras/stad2900"

[Pdot]
value = 0.5203e-15  # s/s
error = 0.0005e-15
ref = "https://doi.org/10.1093/mnras/stad2900"

[Pepoch]
value = 59545
error = false
ref = "https://doi.org/10.1093/mnras/stad2900"

[BurstRate]
[BurstRate.Discovery]
value = 390
error = 108
frequency = 350
telescope = "GBT"
minflux = 160  # mJy
ref = "https://doi.org/10.1088/0004-637X/809/1/67"

[BurstRate.GBT350]
value = 60
error = 15
frequency = 350
telescope = "GBT"
minflux = 160  # mJy
ref = "https://doi.org/10.1088/0004-637X/809/1/67"

[BurstRate.GBT820]
value = 0
error = false
frequency = 820
telescope = "GBT"
minflux = 45  # mJy
ref = "https://doi.org/10.1088/0004-637X/809/1/67"

[BurstRate.LOFAR]
value = 3
error = 2
frequency = 150
telescope = "LOFAR"
minflux = 80  # mJy
ref = "https://doi.org/10.1088/0004-637X/809/1/67"

[BurstRate.LOFAR150]
value = 3.2  # hour^-1
error = 0.3
frequency = 150  # MHz
telescope = "I-LOFAR"
minflux = false  # mJy
ref = "https://doi.org/10.1093/mnras/stad2900"

[Width]
[Width.150]
value = 4.0  # ms
error = 1.4
frequency = 150  # MHz
ref = "https://doi.org/10.1093/mnras/stad2900"

# Karako-Argaman et al 2015: https://doi.org/10.1088/0004-637X/809/1/67
# McKenna et al 2024: https://doi.org/10.1093/mnras/stad2900
