title = "J0103+54"

[Name]
value = "J0103+54"
error = false
ref = "https://doi.org/10.1088/0004-637X/809/1/67"


[RA]
value = "01:03:37" #hh:mm:ss.ss
error = "00:00:20"
ref = "https://doi.org/10.1088/0004-637X/809/1/67"

[Dec]
value = "+54:02" #(sign)dd:mm:ss.ss
error = "00:05"
ref = "https://doi.org/10.1088/0004-637X/809/1/67"

[DM]
value = 55.605 #pc/cc
error = 0.004
ref = "https://doi.org/10.1088/0004-637X/809/1/67"

[Period]
value = 0.354304 #seconds
error = 0.000006
ref = "https://doi.org/10.1088/0004-637X/809/1/67"

[BurstRate]

    [BurstRate.Discovery]
  value= 390
  error= 108
  frequency= 350
  telescope= 'GBT'
  minflux= 160 #mJy
  ref = "https://doi.org/10.1088/0004-637X/809/1/67"

    [BurstRate.GBT350]
  value= 60
  error= 15
  frequency= 350
  telescope= 'GBT'
  minflux= 160 #mJy
  ref = "https://doi.org/10.1088/0004-637X/809/1/67"

    [BurstRate.GBT820]
  value= 0
  error= false
  frequency= 820
  telescope= 'GBT'
  minflux= 45 #mJy
  ref = "https://doi.org/10.1088/0004-637X/809/1/67"

    [BurstRate.LOFAR]
  value= 3
  error= 2
  frequency= 150
  telescope= 'LOFAR'
  minflux= 80 #mJy
  ref = "https://doi.org/10.1088/0004-637X/809/1/67"


##Karako-Argaman et al 2015: https://doi.org/10.1088/0004-637X/809/1/67
