title = "J0121+53"

[Name]
value = "J0121+53"
error = false
ref = "https://arxiv.org/abs/2012.02320"

[RA]
value = "01:21" #hh:mm:ss.ss
error = "00:11"
ref = "https://arxiv.org/abs/2012.02320"

[Dec]
value = "+53:29" #(sign)dd:mm:ss.ss
error = "00:16"
ref = "https://arxiv.org/abs/2012.02320"

[DM]
value = 91.38 #pc/cc
error = 0.03
ref = "https://arxiv.org/abs/2012.02320"

[Period]
value = 2.7247846 #seconds
error = 0.0000004
ref = "https://arxiv.org/abs/2012.02320"

[Flux]

    [Flux.600]
  value = 200 #mJy
  error = 150
  frequency = 600 #MHz
  ref = "https://arxiv.org/abs/2012.02320"

[Width]

    [Width.600]
  value = 20 #ms
  error = 5
  frequency = 600 #MHz
  ref = "https://arxiv.org/abs/2012.02320"

[BurstRate]

    [BurstRate.Discovery]
  value= 2.4 #hour^-1
  error= 0.2
  frequency= 600 #MHz
  telescope= "CHIME"
  minflux= 42 #mJy
  ref = "https://arxiv.org/abs/2012.02320"

#Good et al 2020: https://arxiv.org/abs/2012.02320
