title = "J0447-04"

[Name]
value = "J0447-04"
error = false
ref = "https://doi.org/10.1088/0004-637X/809/1/67"

[RA]
value = "04:47" #hh:mm:ss.ss
error = "00:01"
ref = "https://doi.org/10.1088/0004-637X/809/1/67"

[Dec]
value = "-04:35" #(sign)dd:mm:ss.ss
error = "00:18"
ref = "https://doi.org/10.1088/0004-637X/809/1/67"

[DM]
value =  29.83 #pc/cc
error = 0.04
ref = "https://doi.org/10.1088/0004-637X/809/1/67"

[Period]
value = 2.18819 #seconds
error = 0.00002
ref = "https://doi.org/10.1088/0004-637X/809/1/67"


[BurstRate]

    [BurstRate.Discovery]
  value= 103
  error= 51
  frequency= 350
  telescope= 'GBT'
  minflux= 160 #mJy
  ref = "https://doi.org/10.1088/0004-637X/809/1/67"

    [BurstRate.GBT350]
  value= 41
  error= 10
  frequency= 350
  telescope= 'GBT'
  minflux= 160 #mJy
  ref = "https://doi.org/10.1088/0004-637X/809/1/67"

    [BurstRate.GBT820]
  value= 78
  error= 22
  frequency= 820
  telescope= 'GBT'
  minflux= 45 #mJy
  ref = "https://doi.org/10.1088/0004-637X/809/1/67"

    [BurstRate.LOFAR]
  value= 0
  error= false
  frequency= 150
  telescope= 'LOFAR'
  minflux= 80 #mJy
  ref = "https://doi.org/10.1088/0004-637X/809/1/67"



#Karako-Argaman et al 2015: https://doi.org/10.1088/0004-637X/809/1/67