title = "J0513-04"

[Name]
value = "J0513-04"
error = false
ref = "https://doi.org/10.1088/0004-637X/809/1/67"

[RA]
value = "05:13" #hh:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/0004-637X/809/1/67"

[Dec]
value = "-04:18" #(sign)dd:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/0004-637X/809/1/67"

[DM]
value = 18.5 #pc/cc
error = false
ref = "https://doi.org/10.1088/0004-637X/809/1/67"

[Flux]

    [Flux.350]
  value = 1000 #mJy 
  frequency = 350 #MHz
  error = false
  ref = "https://doi.org/10.1088/0004-637X/809/1/67"


#Karako-Argaman et al 2015: https://doi.org/10.1088/0004-637X/809/1/67