title = "J0545-03"

[Name]
value = "J0545-03"
error = false
ref = "https://doi.org/10.1088/0004-637X/809/1/67"

[RA]
value = "05:45" #hh:mm:ss.ss
error = "00:02"
ref = "https://doi.org/10.1088/0004-637X/809/1/67"

[Dec]
value = "-03:10" #(sign)dd:mm:ss.ss
error = "00:36"
ref = "https://doi.org/10.1088/0004-637X/809/1/67"

[DM]
value =  67.2 #pc/cc
error = 0.4
ref = "https://doi.org/10.1088/0004-637X/809/1/67"

[Period]
value = 1.07393 #seconds
error = 0.00002
ref = "https://doi.org/10.1088/0004-637X/809/1/67"


[BurstRate]

    [BurstRate.Discovery]
  value= 77
  error= 45
  frequency= 350
  telescope= 'GBT'
  minflux= 160 #mJy
  ref = "https://doi.org/10.1088/0004-637X/809/1/67"

    [BurstRate.GBT350]
  value= 42
  error= 16
  frequency= 350
  telescope= 'GBT'
  minflux= 160 #mJy
  ref = "https://doi.org/10.1088/0004-637X/809/1/67"

    [BurstRate.LOFAR]
  value= 0
  error= False
  frequency= 150
  telescope= 'LOFAR'
  minflux= 80 #mJy
  ref = "https://doi.org/10.1088/0004-637X/809/1/67"



#Karako-Argaman et al 2015: https://doi.org/10.1088/0004-637X/809/1/67