title = "J0550+09"

[Name]
value = "J0550+09"
error = false
ref = "https://doi.org/10.3847/0004-637X/821/1/10"

[RA]
value = "05:50:28" #hh:mm:ss.ss
error = "00:01:54"
ref = "https://doi.org/10.3847/0004-637X/821/1/10"

[Dec]
value = "+09:51" #(sign)dd:mm:ss.ss
error = "00:08"
ref = "https://doi.org/10.3847/0004-637X/821/1/10"

[DM]
value = 86.6 #pc/cc
error = false
ref = "https://doi.org/10.3847/0004-637X/821/1/10"

[Period]
value = 1.745 #seconds
error = false
ref = "https://doi.org/10.3847/0004-637X/821/1/10"

[Flux]

    [Flux.327]
  value = 100 #mJy
  error =  false
  frequency = 327 #MHz
  ref = "https://doi.org/10.3847/0004-637X/821/1/10"

[Width]

    [Width.327]
  value = 22.5 #ms
  error = false
  frequency = 327 #MHz
  ref = "https://doi.org/10.3847/0004-637X/821/1/10"

[BurstRate]

    [BurstRate.Discovery]
  value= 47
  error= false
  frequency= 327 #MHz
  telescope= "Arecibo"
  minflux= 60 #mJy
  ref = "https://doi.org/10.3847/0004-637X/821/1/10"

#Deneva et al 2016: https://doi.org/10.3847/0004-637X/821/1/10
