title = "J0614-03"

[Name]
value = "J0614-03"
error = false
ref = "https://doi.org/10.1088/0004-637X/809/1/67"

[RA]
value = "06:15" #hh:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/0004-637X/809/1/67"

[Dec]
value = "-03:29" #(sign)dd:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/0004-637X/809/1/67"

[DM]
value = 17.9 #pc/cc
error = false
ref = "https://doi.org/10.1088/0004-637X/809/1/67"

[Period]
value = 0.136
error = false
ref = "https://doi.org/10.1088/0004-637X/809/1/67"


[Flux]

    [Flux.350]
  value = 900  #mJy 
  frequency = 350 #MHz
  error = false
  ref = "https://doi.org/10.1088/0004-637X/809/1/67"


#Karako-Argaman et al 2015: https://doi.org/10.1088/0004-637X/809/1/67