title = "J0627+16"

[Name]
value = "J0627+16"
error = false
ref = "https://doi.org/10.1088/0004-637X/703/2/2259"

[RA]
value = "06:27:13" #hh:mm:ss.ss
error = "00:00:07"
ref = "https://doi.org/10.1088/0004-637X/703/2/2259"

[Dec]
value = "+16:12" #(sign)dd:mm:ss.ss
error = "00:02"
ref = "https://doi.org/10.1088/0004-637X/703/2/2259"

[DM]
value = 113 #pc/cc
error = false
ref = "https://doi.org/10.1088/0004-637X/703/2/2259"

[Period]
value = 2.180 #seconds
error = false
ref = "https://doi.org/10.1088/0004-637X/703/2/2259"

[Flux]

    [Flux.1400]
  value = 150 #mJy
  error = false
  frequency = 1400 #MHz
  ref = "https://doi.org/10.1088/0004-637X/703/2/2259"

[Width]

    [Width.1400]
  value = 0.3 #ms
  error = false
  frequency = 1400 #MHz
  ref = "https://doi.org/10.1088/0004-637X/703/2/2259"

[BurstRate]

    [BurstRate.Discovery]
  value= 23 #hour^-1
  error= false
  frequency= 1400 #MHz
  telescope= "Arecibo"
  minflux= 60 #mJy
  ref = "https://doi.org/10.1088/0004-637X/703/2/2259"

#Deneva et al 2009: https://doi.org/10.1088/0004-637X/703/2/2259