title = "J0653-06"

[Name]
value = "J0653-06"
error = false
ref = "https://doi.org/10.1093/mnras/stad2012"

[RA]
value = "06:53" #hh:mm:ss.ss
error = "00:01"
ref = "https://doi.org/10.1093/mnras/stad2012"

[Dec]
value = "-6:16" #(sign)dd:mm:ss.ss
error = "0:36"
ref = "https://doi.org/10.1093/mnras/stad2012"

[DM]
value =  83.7 #pc/cc
error = false
ref = "https://doi.org/10.1093/mnras/stad2012"

[Period]
value = 0.79 #seconds
error = false
ref = "https://doi.org/10.1093/mnras/stad2012"


[BurstRate]

    [BurstRate.Discovery]
  value = 1.4 #hour^-1
  error = false
  frequency = 600 #MHz
  telescope = 'CHIME'
  minflux = false#mJy
  ref = "https://doi.org/10.1093/mnras/stad2012"

#References go here
# Dong et al 2023 https://doi.org/10.1093/mnras/stad2012
