title = "J0957-06"

[Name]
value = "J0957-06"
error = false
ref = "https://doi.org/10.1088/0004-637X/809/1/67"

[RA]
value = "09:57" #hh:mm:ss.ss
error = "00:02"
ref = "https://doi.org/10.1088/0004-637X/809/1/67"

[Dec]
value = "-06:17" #(sign)dd:mm:ss.ss
error = "00:36"
ref = "https://doi.org/10.1088/0004-637X/809/1/67"

[DM]
value =  26.95 #pc/cc
error = 0.02
ref = "https://doi.org/10.1088/0004-637X/809/1/67"

[Period]
value = 1.72370 #seconds
error = 0.00008
ref = "https://doi.org/10.1088/0004-637X/809/1/67"

[BurstRate]

    [BurstRate.Discovery]
  value= 180
  error= 68
  frequency= 350
  telescope= 'GBT'
  minflux= 160 #mJy
  ref = "https://doi.org/10.1088/0004-637X/809/1/67"

    [BurstRate.GBT350]
  value= 138
  error= 29
  frequency= 350
  telescope= 'GBT'
  minflux= 160 #mJy
  ref = "https://doi.org/10.1088/0004-637X/809/1/67"

    [BurstRate.LOFAR]
  value= 0
  error= False
  frequency= 150
  telescope= 'LOFAR'
  minflux= 80 #mJy
  ref = "https://doi.org/10.1088/0004-637X/809/1/67"



#Karako-Argaman et al 2015: https://doi.org/10.1088/0004-637X/809/1/67