title = "J1059-01"

[Name]
value = "J1059-01"
error = false
ref = "https://doi.org/10.1088/0004-637X/809/1/67"

[RA]
value = "10:59" #hh:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/0004-637X/809/1/67"

[Dec]
value = "-01:02" #(sign)dd:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/0004-637X/809/1/67"

[DM]
value = 18.7 #pc/cc
error = false
ref = "https://doi.org/10.1088/0004-637X/809/1/67"


[Flux]

    [Flux.350]
  value = 800  #mJy 
  frequency = 350 #MHz
  error = false
  ref = "https://doi.org/10.1088/0004-637X/809/1/67"


#Karako-Argaman et al 2015: https://doi.org/10.1088/0004-637X/809/1/67