title = "J1126-27"

[Name]
value = "J1126-27"
error = false
ref = "https://doi.org/10.1088/0004-637X/809/1/67"

[RA]
value = "11:26" #hh:mm:ss.ss
error = "00:02"
ref = "https://doi.org/10.1088/0004-637X/809/1/67"

[Dec]
value = "-27:37" #(sign)dd:mm:ss.ss
error = "00:36"
ref = "https://doi.org/10.1088/0004-637X/809/1/67"

[DM]
value =  26.860 #pc/cc
error = 0.007
ref = "https://doi.org/10.1088/0004-637X/809/1/67"

[Period]
value = 0.358161 #seconds
error = 0.000008
ref = "https://doi.org/10.1088/0004-637X/809/1/67"

[Flux]

    [Flux.350]
  value= 0.29 #mJy
  error = 0.12
  frequency = 350 #MHz
  ref = "https://doi.org/10.3847/1538-4357/ab75e2"

[Width]

    [Width.350]
  value= 8 #ms
  error = false
  frequency = 350 #MHz
  ref = "https://doi.org/10.3847/1538-4357/ab75e2"

[BurstRate]

    [BurstRate.Discovery]
  value= 180
  error= 73
  frequency= 350
  telescope= 'GBT'
  minflux= 160 #mJy
  ref = "https://doi.org/10.1088/0004-637X/809/1/67"

    [BurstRate.GBT350]
  value= 48
  error= 17
  frequency= 350
  telescope= 'GBT'
  minflux= 160 #mJy
  ref = "https://doi.org/10.1088/0004-637X/809/1/67"




#Karako-Argaman et al 2015: https://doi.org/10.1088/0004-637X/809/1/67
#McEwen et al 2020: https://doi.org/10.3847/1538-4357/ab75e2