title = "J1153-21"

[Name]
value = "J1153-21"
error = false
ref = "https://doi.org/10.1088/0004-637X/809/1/67"

[RA]
value = "11:53" #hh:mm:ss.ss
error = "00:02"
ref = "https://doi.org/10.1088/0004-637X/809/1/67"

[Dec]
value = "-21:18" #(sign)dd:mm:ss.ss
error = "00:36"
ref = "https://doi.org/10.1088/0004-637X/809/1/67"

[DM]
value =  34.8 #pc/cc
error = 0.1
ref = "https://doi.org/10.1088/0004-637X/809/1/67"

[Period]
value = 2.34348 #seconds
error = 0.00005
ref = "https://doi.org/10.1088/0004-637X/809/1/67"

[BurstRate]

    [BurstRate.Discovery]
  value= 150
  error= 67
  frequency= 350
  telescope= 'GBT'
  minflux= 160 #mJy
  ref = "https://doi.org/10.1088/0004-637X/809/1/67"

    [BurstRate.GBT350]
  value= 60
  error= 24
  frequency= 350
  telescope= 'GBT'
  minflux= 160 #mJy
  ref = "https://doi.org/10.1088/0004-637X/809/1/67"



#Karako-Argaman et al 2015: https://doi.org/10.1088/0004-637X/809/1/67