title = "J1354+24"

[Name]
value = "J1354+24"
error = false
ref = "https://doi.org/10.1088/0004-637X/809/1/67"

[RA]
value = "13:54" #hh:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/0004-637X/809/1/67"

[Dec]
value = "+24:54" #(sign)dd:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/0004-637X/809/1/67"

[DM]
value = 20.0 #pc/cc
error = false
ref = "https://doi.org/10.1088/0004-637X/809/1/67"


[Flux]

    [Flux.350]
  value = 100  #mJy 
  frequency = 350 #MHz
  error = false
  ref = "https://doi.org/10.1088/0004-637X/809/1/67"


#Karako-Argaman et al 2015: https://doi.org/10.1088/0004-637X/809/1/67