title = "J1433+00"

[Name]
value = "J1433+00"
error = false
ref = "https://doi.org/10.3847/0004-637X/821/1/10"

[RA]
value = "14:33:30" #hh:mm:ss.ss
error = "00:01:53"
ref = "https://doi.org/10.3847/0004-637X/821/1/10"

[Dec]
value = "+00:28" #(sign)dd:mm:ss.ss
error = "00:08"
ref = "https://doi.org/10.3847/0004-637X/821/1/10"

[DM]
value = 23.5 #pc/cc
error = False
ref = "https://doi.org/10.3847/0004-637X/821/1/10"

[Flux]

    [Flux.327]
  value = 3.8 #mJy
  error = False
  frequency = 327 #MHz
  ref = "https://doi.org/10.3847/0004-637X/821/1/10"

[Width]

    [Width.327]
  value = 3.8 #ms
  error = False
  frequency = 327 #MHz
  ref = "https://doi.org/10.3847/0004-637X/821/1/10"

[BurstRate]

    [BurstRate.Discovery]
  value= 2
  error= False
  frequency= 327 #MHz
  telescope= "Arecibo"
  minflux= 150 #mJy
  ref = "https://doi.org/10.3847/0004-637X/821/1/10"

#Deneva et al 2016: https://doi.org/10.3847/0004-637X/821/1/10
