title = "J1705-04"

[Name]
value = "J1705-04"
error = false
ref = "https://doi.org/10.1088/0004-637X/809/1/67"

[RA]
value = "17:05" #hh:mm:ss.ss
error = "00:02"
ref = "https://doi.org/10.1088/0004-637X/809/1/67"

[Dec]
value = "-04:41" #(sign)dd:mm:ss.ss
error = "00:36"
ref = "https://doi.org/10.1088/0004-637X/809/1/67"

[DM]
value = 42.951 #pc/cc
error =  0.009
ref = "https://doi.org/10.1088/0004-637X/809/1/67"

[Period]
value = 0.23748 #seconds
error = 0.00002
ref = "https://doi.org/10.1088/0004-637X/809/1/67"

[BurstRate]

    [BurstRate.Discovery]
  value= 26
  error= 26
  frequency= 350
  telescope= 'GBT'
  minflux= 160 #mJy
  ref = "https://doi.org/10.1088/0004-637X/809/1/67"

    [BurstRate.GBT350]
  value= 32
  error= 11
  frequency= 350
  telescope= 'GBT'
  minflux= 160 #mJy
  ref = "https://doi.org/10.1088/0004-637X/809/1/67"

    [BurstRate.LOFAR]
  value= 0
  error= False
  frequency= 150
  telescope= 'LOFAR'
  minflux= 80 #mJy
  ref = "https://doi.org/10.1088/0004-637X/809/1/67"



#Karako-Argaman et al 2015: https://doi.org/10.1088/0004-637X/809/1/67