title = "J1754-3014"

[Name]
value = "J1754-3014"
error = false
ref = "https://doi.org/10.1038/nature04440"

[RA]
value = "17:54:30.181" #hh:mm:ss.ss
error = "00:00:00.040"
ref = "https://doi.org/10.3847/1538-4357/aa88c3"

[Dec]
value = "-30:15:03" #(sign)dd:mm:ss.ss
error = "00:00:05"
ref = "https://doi.org/10.3847/1538-4357/aa88c3"

[DM]
value = 89.70 #pc/cc
error = 0.07
ref = "https://doi.org/10.3847/1538-4357/aa88c3"

[Period]
value = 1.3204904144 #seconds
error = 0.0000000003
ref = "https://doi.org/10.3847/1538-4357/aa88c3"

[Pdot]
value = 4.428e-15 #s/s
error = 0.019e-15
ref = "https://doi.org/10.3847/1538-4357/aa88c3"

[Flux]

    [Flux.1400]
  value = 160 #mJy
  error = false
  frequency = 1400 #MHz
  ref = "https://doi.org/10.1038/nature04440"

[Width]

    [Width.820]
  value = 36 #ms
  error = false
  frequency = 820 #MHz
  ref = "https://doi.org/10.3847/1538-4357/aa88c3"

    [Width.1400]
  value = 16 #ms
  error = false
  frequency = 1400 #MHz
  ref = "https://doi.org/10.1038/nature04440"

[BurstRate]

    [BurstRate.Discovery]
  value= 0.6 #hour^-1
  error= false
  frequency= 1400 #MHz
  telescope= "Parkes"
  minflux= 70 #mJy
  ref = "https://doi.org/10.1038/nature04440"

    [BurstRate.Cui]
  value = 79.79 #hour^-1
  error = false
  frequency = 820 #MHz
  telescope = "GBT"
  minflux = 45 #mJy
  ref = "https://doi.org/10.3847/1538-4357/aa6aa9"

    [BurstRate.Jiang]
  value = 120.3 #hour^-1
  error = false
  frequency = 820 #MHz
  telescope = "GBT"
  minflux = 45 #mJy
  ref = "https://doi.org/10.3847/1538-4357/aa88c3"

#McLaughlin et al 2006: https://doi.org/10.1038/nature04440
#Jiang et al 2017: https://doi.org/10.3847/1538-4357/aa88c3
#Cui et al 2017 https://doi.org/10.3847/1538-4357/aa6aa9