title = "J1856+09"

[Name]
value = "J1856+09"
error = false
ref = "https://doi.org/10.3847/1538-4357/aaee65"

[RA]
value = "18:56" #hh:mm:ss.ss
error = false
ref = "https://doi.org/10.3847/1538-4357/aaee65"

[Dec]
value = "+09" #(sign)dd:mm:ss.ss
error = false
ref = "https://doi.org/10.3847/1538-4357/aaee65"

[DM]
value = 193.4 #pc/cc
error = 0.6
ref = "https://doi.org/10.3847/1538-4357/aaee65"

[Period]
value = 2.17071 #seconds
error = 0.00011
ref = "https://doi.org/10.3847/1538-4357/aaee65"

[Flux]

    [Flux.1400]
  value = 48 #mJy
  error = false
  frequency = 1400 #MHz
  ref = "https://doi.org/10.3847/1538-4357/aaee65"

[Width]

    [Width.1400]
  value = 4 #ms
  error = false
  frequency = 1400 #MHz
  ref = "https://doi.org/10.3847/1538-4357/aaee65"


#Deneva et al 2018: https://doi.org/10.3847/1538-4357/aaee65
