title = "J1928+15"

[Name]
value = "J1928+15"
error = false
ref = "https://doi.org/10.1088/0004-637X/703/2/2259"

[RA]
value = "19:28:20" #hh:mm:ss.ss
error = "00:00:07"
ref = "https://doi.org/10.1088/0004-637X/703/2/2259"

[Dec]
value = "+15:13" #(sign)dd:mm:ss.ss
error = "00:02"
ref = "https://doi.org/10.1088/0004-637X/703/2/2259"

[DM]
value = 242 #pc/cc
error = false
ref = "https://doi.org/10.1088/0004-637X/703/2/2259"

[Period]
value = 0.403 #seconds
error = false
ref = "https://doi.org/10.1088/0004-637X/703/2/2259"

[Flux]

    [Flux.1400]
  value = 180  #mJy
  error = false
  frequency = 1400 #MHz
  ref = "https://doi.org/10.1088/0004-637X/703/2/2259"

[Width]

    [Width.1400]
  value = 5 #ms
  error = false
  frequency = 1400 #MHz
  ref = "https://doi.org/10.1088/0004-637X/703/2/2259"

[BurstRate]

    [BurstRate.Discovery]
  value= 4 #hour^-1
  error= false
  frequency= 1400 #MHz
  telescope= "Arecibo"
  minflux= 14 #mJy
  ref = "https://doi.org/10.1088/0004-637X/703/2/2259"

#Deneva et al 2009: https://doi.org/10.1088/0004-637X/703/2/2259