title = "J1958+30"

[Name]
value = "J1958+30"
error = false
ref = "https://doi.org/10.3847/1538-4357/aaee65"

[RA]
value = "19:58" #hh:mm:ss.ss
error = false
ref = "https://doi.org/10.3847/1538-4357/aaee65"

[Dec]
value = "+30" #(sign)dd:mm:ss.ss
error = false
ref = "https://doi.org/10.3847/1538-4357/aaee65"

[DM]
value = 199.3 #pc/cc
error = 0.4
ref = "https://doi.org/10.3847/1538-4357/aaee65"

[Period]
value = 1.09853 #seconds
error = 0.00002
ref = "https://doi.org/10.3847/1538-4357/aaee65"

[Flux]

    [Flux.1400]
  value = 54 #mJy
  error = false
  frequency = 1400 #MHz
  ref = "https://doi.org/10.3847/1538-4357/aaee65"

[Width]

    [Width.1400]
  value = 4 #ms
  error = false
  frequency = 1400 #MHz
  ref = "https://doi.org/10.3847/1538-4357/aaee65"


#Deneva et al 2018: https://doi.org/10.3847/1538-4357/aaee65
