title = "J2000+29"

[Name]
value = "J2000+29"
error = false
ref = "https://doi.org/10.3847/1538-4357/aaee65"

[RA]
value = "20:00" #hh:mm:ss.ss
error = false
ref = "https://doi.org/10.3847/1538-4357/aaee65"

[Dec]
value = "+29" #(sign)dd:mm:ss.ss
error = false
ref = "https://doi.org/10.3847/1538-4357/aaee65"

[DM]
value = 132.5 #pc/cc
error = 1.4
ref = "https://doi.org/10.3847/1538-4357/aaee65"

[Period]
value = 3.07370 #seconds
error = 0.00014
ref = "https://doi.org/10.3847/1538-4357/aaee65"

[Flux]

    [Flux.1400]
  value = 159 #mJy
  error = false
  frequency = 1400 #MHz
  ref = "https://doi.org/10.3847/1538-4357/aaee65"

[Width]

    [Width.1400]
  value = 7.4 #ms
  error = false
  frequency = 1400 #MHz
  ref = "https://doi.org/10.3847/1538-4357/aaee65"


#Deneva et al 2018: https://doi.org/10.3847/1538-4357/aaee65
