title = "J2215+4524"

[Name]
value = "J2215+4524"
error = false
ref = "https://doi.org/10.1093/mnras/stad2012"

[RA]
value = "22:15:46.57" #hh:mm:ss.ss
error = "00:00:00.07"
ref = "https://doi.org/10.1093/mnras/stad2012"

[Dec]
value = "+45:24:44" #(sign)dd:mm:ss.ss
error = "00:00:02"
ref = "https://doi.org/10.1093/mnras/stad2012"

[DM]
value =  #pc/cc
error = 
ref = "https://doi.org/10.1093/mnras/stad2012"

[Period]
value = 2.7230498235 #seconds
error = 0.0000000003
ref = "https://doi.org/10.1093/mnras/stad2012"

[Pdot]
value = 5.6e-15 #s/s
error = 0.2e-15
ref = "https://doi.org/10.1093/mnras/stad2012"

[Pepoch]
value = 59241
error = false
ref = "https://doi.org/10.1093/mnras/stad2012"


[BurstRate]

    [BurstRate.Discovery]
  value = 6.0 #hour^-1
  error = false
  frequency = 600 #MHz
  telescope = CHIME
  minflux = false#mJy
  ref = "https://doi.org/10.1093/mnras/stad2012"

#References go here
# Dong et al 2023 https://doi.org/10.1093/mnras/stad2012

