title = ""

[Name]
value = ""
error = false
ref = ""

[RA]
value = "" #hh:mm:ss.ss
error = ""
ref = ""

[Dec]
value = "" #(sign)dd:mm:ss.ss
error = ""
ref = ""

[DM]
value =  #pc/cc
error = 
ref = ""

[Period]
value = #seconds
error = 
ref = ""

[Pdot]
value = #s/s
error = 
ref = ""

[Flux]

    [Flux.1400]
  value = #mJy
  error =  
  frequency = #MHz
  ref = ""

[Width]

    [Width.1400]
  value = #ms
  error = 
  frequency = #MHz
  ref = ""

[BurstRate]

    [BurstRate.Discovery]
  value= #hour^-1
  error=
  frequency= #MHz
  telescope=
  minflux= #mJy
  ref = ""

#References go here
